upstream backend_servers {
    server web_backend_1:80;
    server web_backend_2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        
        # Capçaleres per identificar el backend
        add_header X-Backend-Server $upstream_addr;
        add_header X-Served-By "Proxy-Nginx";
    }
}